name: play with drill gradle plguin (version)
on:
  push:
    tags:
      - 'v[0-9]*.[0-9]*.[0-9]*'

jobs:

  linux_job:
    name: Check Linux platform
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: set
        run: echo ::set-env name=RELEASE_VERSION::${GITHUB_REF:10}
      - name: Test
        run: |
          git describe --tags --match v[0-9]*.[0-9]*.[0-9]*
          echo $RELEASE_VERSION
          echo ${{ env.RELEASE_VERSION }}
          echo ${GITHUB_REF:11}
          echo ${GITHUB_SHA:0:7}
      - name: print env version
        run: gradle -Pversion=${GITHUB_REF:11} printVersion
      - name: printVersion
        run: gradle printVersion
      - name: script
        run: |
          cd .gradle
          ls .
          pwd
          npm --version
