name: play with drill gradle plguin (version)
on:
  push:
    tags:
      - 'v*'

jobs:

  linux_job:
    name: Check Linux platform
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: set
        run: echo ::set-env name=RELEASE_VERSION::${GITHUB_REF:10}
      - name: Test
        run: |
          echo $RELEASE_VERSION
          echo ${{ env.RELEASE_VERSION }}
      - name: printVersion
        run: gradle printVersion